"use client";

import { motion } from "framer-motion";
import { CheckCircle2, ExternalLink, Loader2 } from "lucide-react";
import { ErrorBox, StepPanel } from "@/components/modals/transaction-modal-shell";

export function ReceiptStep({
  error,
  opening,
  onClose,
  onOpenReceipt,
  receipt,
}: {
  error: string | null;
  opening: boolean;
  onClose: () => void;
  onOpenReceipt: () => Promise<void>;
  receipt: { transactionId: string; receiptUrl?: string } | null;
}) {
  return (
    <StepPanel>
      <div className="py-5 text-center">
        <motion.div initial={{ scale: 0.8 }} animate={{ scale: 1 }} className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-full bg-[#50fa7b]/15">
          <CheckCircle2 className="h-8 w-8 text-[#50fa7b]" />
        </motion.div>
        <h3 className="text-2xl font-black text-white">Transfer committed</h3>
        <p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-[#a7b0c8]">The receipt PDF was generated by the API and attached to the debit transaction.</p>
        {receipt?.transactionId ? <ReceiptReference transactionId={receipt.transactionId} /> : null}
        {error ? <div className="mt-4"><ErrorBox message={error} /></div> : null}
        <div className="mt-6 grid gap-3 sm:grid-cols-2">
          <button onClick={onOpenReceipt} disabled={!receipt?.transactionId || opening} className="btn-cashout flex h-12 items-center justify-center gap-2 text-sm font-bold disabled:opacity-60">
            {opening ? <Loader2 className="h-4 w-4 animate-spin" /> : <ExternalLink className="h-4 w-4" />}
            Open PDF receipt
          </button>
          <button onClick={onClose} className="chip-btn h-12 px-6 text-sm font-bold">Close</button>
        </div>
      </div>
    </StepPanel>
  );
}

function ReceiptReference({ transactionId }: { transactionId: string }) {
  return (
    <div className="mt-5 rounded-2xl border border-white/10 bg-black/20 p-3 text-left">
      <p className="text-xs uppercase tracking-[0.2em] text-[#a7b0c8]">Receipt transaction</p>
      <p className="mt-2 break-all font-mono text-xs text-[#8be9fd]">{transactionId}</p>
    </div>
  );
}
